### ISSUE TITLE
unable to find an inherited method for function ‘select’ for signature ‘"tbl_df"

### ISSUE THREAD

**Issue by chris-kreitzer** [beroukhim-lab/ascets#1]
Hi Liam,

Firstly, I want to express my appreciation on your code - **ascets**. The code chunk is clear, concise and indeed provide the community with a needed tool :)

However, I just cloned your repository and tried my first approach in making some calls. I immediately failed -- due to the error mentioned above `unable to find an inherited method for function ‘select’ for signature ‘"tbl_df"`. I rarely use 'Hadley's world' (therefore it might be a silly announcement in here), but I exchanged the **select()** within the ascets_resources.R to **dplyr::select()** and all of a sudden it runs just smoothly. 

I thought I should mention it, as there might some people also stumble across the same issue... :)

best,
chris.

**Comment by lfspurr** [comment]
Hi Chris,

Thanks for bringing this to my attention. Were you running ASCETS from within R Studio? I've found if I have another genomics-related package like GenomicRanges loaded it often overwrites the select (and some other functions) in the tidyverse because they have functions of the same name and as a result I have seen bugs like this too. 

Liam

**Comment by chris-kreitzer** [comment]
Hi Liam, 

Yeah I am running ASCETS from within R Studio (is working pretty neatly) :)
I think the best work-around for the 'problems' you are describing (including mine) is to write the package name in front of the function; e.g.
`dplyr::select()`, rather than just `select()` - this will certainly circumvent any related error!

Best,
chris

**Comment by lfspurr** [comment]
This issue is now fixed in v1.1.1
